import type { Metadata, Viewport } from 'next';

import { content, type Locale } from './content';
import { metaKeywords } from './keywords';
import { CONTACTS, PRODUCTS, SITE, SOCIALS } from './constants';

/** BCP-47 tags. The URL segment stays `kz`; the language is `kk`. */
export const htmlLang = (locale: Locale) => (locale === 'kz' ? 'kk' : 'ru');
const ogLocale = (locale: Locale) => (locale === 'kz' ? 'kk_KZ' : 'ru_RU');

export const viewport: Viewport = {
  themeColor: [
    { media: '(prefers-color-scheme: light)', color: '#9561e9' },
    { media: '(prefers-color-scheme: dark)', color: '#9561e9' },
  ],
  width: 'device-width',
  initialScale: 1,
  // Never lock zoom below 5x — pinch-zoom is an accessibility requirement.
  maximumScale: 5,
  colorScheme: 'dark',
};

/**
 * Icon set covering browser tabs, every iOS device generation, Android
 * densities, Windows tiles and the PWA install prompt. Files are generated by
 * `npm run icons` from `public/favicon-source.svg`.
 */
const icons: Metadata['icons'] = {
  icon: [
    { url: '/favicon.ico', sizes: 'any' },
    { url: '/favicon-16x16.png', sizes: '16x16', type: 'image/png' },
    { url: '/favicon-32x32.png', sizes: '32x32', type: 'image/png' },
    { url: '/favicon-48x48.png', sizes: '48x48', type: 'image/png' },
    { url: '/favicon-96x96.png', sizes: '96x96', type: 'image/png' },
    { url: '/icons/android-icon-192x192.png', sizes: '192x192', type: 'image/png' },
    { url: '/icons/android-icon-512x512.png', sizes: '512x512', type: 'image/png' },
  ],
  apple: [
    { url: '/apple-touch-icon-57x57.png', sizes: '57x57' },
    { url: '/apple-touch-icon-60x60.png', sizes: '60x60' },
    { url: '/apple-touch-icon-72x72.png', sizes: '72x72' },
    { url: '/apple-touch-icon-76x76.png', sizes: '76x76' },
    { url: '/apple-touch-icon-114x114.png', sizes: '114x114' },
    { url: '/apple-touch-icon-120x120.png', sizes: '120x120' },
    { url: '/apple-touch-icon-144x144.png', sizes: '144x144' },
    { url: '/apple-touch-icon-152x152.png', sizes: '152x152' },
    { url: '/apple-touch-icon-167x167.png', sizes: '167x167' },
    { url: '/apple-touch-icon-180x180.png', sizes: '180x180' },
  ],
  other: [{ rel: 'mask-icon', url: '/safari-pinned-tab.svg', color: '#9561e9' }],
};

export function buildMetadata(locale: Locale): Metadata {
  const c = content[locale];

  return {
    metadataBase: new URL(SITE.url),
    title: {
      default: c.meta.home_title,
      template: `%s | LOOP Energy Kazakhstan`,
    },
    description: c.meta.home_description,
    keywords: metaKeywords(locale),
    applicationName: SITE.name,
    authors: [{ name: SITE.name, url: SITE.url }],
    creator: SITE.name,
    publisher: SITE.name,
    category: 'shopping',
    icons,
    manifest: '/manifest.json',
    alternates: {
      canonical: `/${locale}`,
      languages: { ru: '/ru', kk: '/kz', 'x-default': '/ru' },
    },
    openGraph: {
      type: 'website',
      siteName: SITE.name,
      locale: ogLocale(locale),
      alternateLocale: locale === 'kz' ? 'ru_RU' : 'kk_KZ',
      url: `${SITE.url}/${locale}`,
      title: c.meta.og_title,
      description: c.meta.og_description,
      images: [{ url: '/og-image.png', width: 1200, height: 630, alt: c.meta.og_image_alt }],
    },
    twitter: {
      card: 'summary_large_image',
      title: c.meta.og_title,
      description: c.meta.og_description,
      images: ['/og-image.png'],
    },
    robots: {
      index: true,
      follow: true,
      googleBot: { index: true, follow: true, 'max-image-preview': 'large', 'max-snippet': -1 },
    },
    other: {
      'msapplication-TileColor': '#201b24',
      'msapplication-TileImage': '/icons/ms-icon-144x144.png',
      'msapplication-config': '/browserconfig.xml',
      'msapplication-navbutton-color': '#9561e9',
      'mobile-web-app-capable': 'yes',
      'apple-mobile-web-app-capable': 'yes',
      'apple-mobile-web-app-status-bar-style': 'black-translucent',
      'apple-mobile-web-app-title': 'LOOP Energy',
      'application-name': 'LOOP Energy KZ',
    },
  };
}

/**
 * Structured data graph. FAQPage pulls from the same copy the page renders, so
 * a rich result can never drift from what a visitor actually sees.
 */
export function buildJsonLd(locale: Locale) {
  const c = content[locale];
  const base = `${SITE.url}/${locale}`;
  const lang = htmlLang(locale);

  const faqPairs = [
    ...c.faq.items.map((item) => ({ q: item.question, a: item.answer })),
    ...c.answers.items.map((item) => ({ q: item.question, a: item.answer })),
  ];

  return {
    '@context': 'https://schema.org',
    '@graph': [
      {
        '@type': 'Organization',
        '@id': `${SITE.url}#organization`,
        name: 'LOOP Energy Kazakhstan',
        alternateName: SITE.name,
        url: SITE.url,
        description: c.meta.home_description,
        logo: { '@type': 'ImageObject', url: `${SITE.url}/icons/android-icon-512x512.png`, width: 512, height: 512 },
        image: `${SITE.url}/og-image.png`,
        areaServed: { '@type': 'Country', name: 'Kazakhstan' },
        knowsLanguage: ['ru', 'kk'],
        contactPoint: [
          {
            '@type': 'ContactPoint',
            contactType: 'sales',
            telephone: CONTACTS.phone.label,
            email: CONTACTS.email.label,
            availableLanguage: ['ru', 'kk'],
            areaServed: 'KZ',
          },
        ],
        sameAs: SOCIALS.map((s) => s.href),
      },
      {
        '@type': 'WebSite',
        '@id': `${SITE.url}#website`,
        url: SITE.url,
        name: SITE.name,
        inLanguage: lang,
        publisher: { '@id': `${SITE.url}#organization` },
      },
      {
        '@type': 'FAQPage',
        '@id': `${base}#faq`,
        inLanguage: lang,
        mainEntity: faqPairs.map((pair) => ({
          '@type': 'Question',
          name: pair.q,
          acceptedAnswer: { '@type': 'Answer', text: pair.a },
        })),
      },
      {
        '@type': 'ItemList',
        '@id': `${base}#catalog`,
        name: `${c.products.h2} ${c.products.h2_accent}`,
        numberOfItems: c.products.items.length,
        itemListElement: c.products.items.map((item, index) => ({
          '@type': 'ListItem',
          position: index + 1,
          item: {
            '@type': 'Product',
            name: item.name,
            description: item.description,
            image: PRODUCTS.find((p) => p.id === item.id)?.image,
            brand: { '@type': 'Brand', name: 'LOOP Energy' },
            offers: {
              '@type': 'Offer',
              price: item.price,
              priceCurrency: 'KZT',
              availability: 'https://schema.org/InStock',
              url: `${base}#products`,
              seller: { '@id': `${SITE.url}#organization` },
            },
          },
        })),
      },
    ],
  };
}
